#!/usr/bin/env python3

import coverage
import re
import shutil
import os

to_delete = []

try:
    old_gps = coverage.python.get_python_source
    def new_gps(filename):
        root, ext = os.path.splitext(filename)
        if(ext == '.mash'):
            mash_filename = filename
            py_filename = root + '.py'
            with open(mash_filename, 'r') as mash_file:
                mash_code = mash_file.read()
            
            py_code = mash_code
            py_code = re.sub(r'\[\[\[', '', py_code)
            py_code = re.sub(r'\|\|\|', '', py_code)
            py_code = re.sub(r'\]\]\]', '', py_code)

            with open(py_filename, 'w') as py_file:
                print(py_code, file=py_file)
            to_delete.append(py_filename)

        else:
            py_filename = filename

        return old_gps(py_filename)

    coverage.python.get_python_source = new_gps

    cov = coverage.Coverage()
    cov.load()
    cov.report(show_missing=True, omit=['/usr*', '/opt*', '*dummy*'])

finally:
    for filename in to_delete:
        os.remove(filename)
